### ISSUE TITLE
Can I skip certain collections?

### ISSUE THREAD

**Issue by hustcer** [sheharyarn/mongo-sync#14]
Thanks for the great work!
BTW: Can I skip certain collections?

**Comment by sheharyarn** [comment]
Hi. Thank you for using `mongo-sync`. [This Issue has been raised before](https://github.com/sheharyarn/mongo-sync/issues/5), but I'm intentionally not implementing this. Please read the reasons in the issue's thread.

For finer control over how your database should be dumped/restored, using `mongodump` and `mongorestore` is recommended. Alternatively, you can [fork](https://github.com/sheharyarn/mongo-sync/fork) the project and add the relevant flags yourself.
