### ISSUE TITLE
Error connecting to remote server

### ISSUE THREAD

**Issue by anandreddyks** [sheharyarn/mongo-sync#16]
assertion: 18 { ok: 0.0, errmsg: "auth failed", code: 18 }
Error on or near line 170; exiting with status 1

**Comment by sheharyarn** [comment]
Hi there,
This doesn't seem like a bug and just that the credentials passed were wrong, or the authorization failed for some other reason.

You can't just post the error code. You'll need to give more details about the server/database you're connecting to and tell what else you have tried.

**Comment by sheharyarn** [comment]
I'm closing this because of lack of details and no follow up from the author.
