### ISSUE TITLE
AuthenticationDatabase parameter for Mongo 3.4+

### ISSUE THREAD

**Issue by humblepride** [sheharyarn/mongo-sync#19]
like this:
`LOCAL_CREDENTIALS="-u $local_access_username -p $local_access_password --authenticationDatabase admin"`
`REMOTE_CREDENTIALS="-u $remote_access_username -p $remote_access_password --authenticationDatabase admin"`

**Comment by sheharyarn** [comment]
Thank you for opening this issue, but please see PR #20 that tries to add this feature:

> The main design goal of this project is to provide a very minimal set of features to easily dump/restore mongo databases. To this end, I've deliberately not added options that don't appeal to the majority of the users. But this also allows others to extend the script according to their specific use-cases without a lot of effort, just like you did.

You can also download @j0e1in's [customized version of the script](https://github.com/j0e1in/mongo-sync) that addresses this.

---

I haven't used MongoDB in quite a while, but if other users believe this is an extremely important feature, we might open the PR again and merge it.
