### ISSUE TITLE
Using Local DB without credentials

### ISSUE THREAD

**Issue by cdcv** [sheharyarn/mongo-sync#23]
I am trying to sync to a local mongo db that doesn't use authentication (no username/pw).  Is there already a way to do this?  If not... can I suggest it as an addition?

Thank you for this lovely tool.

**Comment by sheharyarn** [comment]
Hi @cdcv,
You can use mongo-sync with a local database without specifying the `access` parameters in the `config.yml` file if [Access Control hasn't been enabled](https://stackoverflow.com/a/38921949/1533054) (i.e. there are no credentials to specify).

Here's a minimal example of `config.yml` that does not use credentials for the local database:

https://github.com/sheharyarn/mongo-sync/blob/1ae2aef4a8b40960be5c036e55af228f3351914a/config.yml#L1-L16
