### ISSUE TITLE
Can i use this script on Windows?

### ISSUE THREAD

**Issue by alexjidras** [sheharyarn/mongo-sync#25]
![image](https://user-images.githubusercontent.com/33176605/51854343-3fab3580-2333-11e9-8ff1-f851223fbb3b.png)

**Comment by sheharyarn** [comment]
Hey @alexjidras.

I haven't tested this on Windows but it should work as long as you have `mongodump` and `mongorestore` installed and available in the `PATH`.

You should also keep in mind that [some users have reported issues with the TMP directory](https://github.com/sheharyarn/mongo-sync/issues/6) on windows.

**Comment by alexjidras** [comment]
by default this variables are not in path, would be great if you provide some setup instructions for this platform

**Comment by sheharyarn** [comment]
You should refer to the installation instructions on the official website. See this: https://docs.mongodb.com/manual/tutorial/install-mongodb-on-windows/
