### ISSUE TITLE
Is it really a sync ? 

### ISSUE THREAD

**Issue by nitinsurana** [sheharyarn/mongo-sync#4]
I'm unable to understand - how is it a sync, when it uses mongodump and mongorestore to replace the entire db.

**Comment by sheharyarn** [comment]
No, it isn't. But `mongo-sync` is a nice name. If you take a look at the [Todo Section](https://github.com/sheharyarn/mongo-sync#todo) in the Readme, I plan to add a `--no-overwrite` flag which would most closely resemble a _sync_.
