### ISSUE TITLE
Failed: error connecting to db server: no reachable servers

### ISSUE THREAD

**Issue by impanda-cookie** [sheharyarn/mongo-sync#8]
Hi sheharyarn,

  my mongodb authorization required.
  when run the script `./mongo-sync pull` will throw errors(_config.yml user connected mongodb is okay_):

```
Overwriting Local DB...
2016-02-01T17:28:39.664+0800    Failed: error connecting to db server: no reachable servers
Error on or near line 133; exiting with status 1
Cleaning up...
```

All logs:

> Dumping Remote DB to /tmp/mydb/dump...
> 2016-02-01T17:28:35.408+0800    writing admin.system.indexes to /tmp/mydb/dump/admin/system.indexes.bson
> 2016-02-01T17:28:35.597+0800    done dumping admin.system.indexes (3 documents)
> 2016-02-01T17:28:35.598+0800    writing admin.system.users to /tmp/mydb/dump/admin/system.users.bson
> 2016-02-01T17:28:35.725+0800    done dumping admin.system.users (9 documents)
> 2016-02-01T17:28:35.725+0800    writing admin.system.version to /tmp/mydb/dump/admin/system.version.bson
> 2016-02-01T17:28:36.041+0800    done dumping admin.system.version (1 document)
> Success!
> 
> Overwriting Local DB...
> 2016-02-01T17:28:39.664+0800    Failed: error connecting to db server: no reachable servers
> Error on or near line 133; exiting with status 1
> Cleaning up...

**Comment by sheharyarn** [comment]
My last commit should fix this. Try again. If that doesn't work, make sure your local MongoDB is running and the port is defined in `config.yml`.
